#!/bin/bash

while IFS= read -r -d $'\0' ARG; do
    if test "$ARG" == '--no-verify'; then
        exit 0
    fi
done < /proc/$PPID/cmdline

# Update readme
printf "# My bloated build of st\n\n" > README.md
printf "## Applied patches\n\n" >> README.md
./appliedpatches.sh | xargs -I {} printf " - {}\n" >> README.md
git add README.md
git commit --amend --no-edit --no-verify
printf "Updated README.md\n"
